namespace: ansible
name: fortios
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.netcommon: '>=1.0'
  ansible.misc: '>=1.0'
repository: git@github.com:coll-test/ansible.fortios.git
documentation: https://github.com/coll-test/ansible.fortios/tree/master/docs
homepage: https://github.com/coll-test/ansible.fortios
issues: https://github.com/coll-test/ansible.fortios/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
